In [6]:
#matrix operation
import numpy as np
#create matrix
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#Addition
print("ADD: ")
C=A+B
print(C)
#substraction
print("\n\nSUBSTRACTION:")
D=A-B
print(D)

#Multiplication(element-wise)
print("\n\nMULTIPLICATION  :")
E=A*B
print(E)
#Matrix multplication
print("\n\nMATRIX_MULTIPLICATION  :")
F=np.dot(A,B)# or A @ B
print(F)
#Transpose
print("\n\nTRANSPOSE  :")
A_transpose=A.T
print(A_transpose)


ADD: 
[[ 6  8]
 [10 12]]


SUBSTRACTION:
[[-4 -4]
 [-4 -4]]


MULTIPLICATION  :
[[ 5 12]
 [21 32]]


MATRIX_MULTIPLICATION  :
[[19 22]
 [43 50]]


TRANSPOSE  :
[[1 3]
 [2 4]]


In [ ]:
#SVD(Singular Value Decomposition)
import numpy as np
#create a sample materix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
U,S,VT=np.linalg.svd(X)
#choose the number of components to keep
n_components=2
#Reconstructed the matrix with reduced dimensions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),
VT[:n_components,:]))
print("original Matrix:");
print(X)
print("\nReconstructed Matrix(with reduced dimension):")
print(X_reconstructed)